### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by ItzSkyReed** [BoBkiNN/AdvancementWorldBorder#1]
Мне очень понравился твой плагин, и было бы круто, если бы ты добавил возможность каждому достижению давать разное количество блоков на которое он будет увеличиваться.

Ну и на 1.19 обновить, хотя в целом он и так работает

**Comment by BoBkiNN** [comment]
> Мне очень понравился твой плагин, и было бы круто, если бы ты добавил возможность каждому достижению давать разное количество блоков на которое он будет увеличиваться.
> 
> Ну и на 1.19 обновить, хотя в целом он и так работает

Спасибо, если будет время то сделаю обновление
